[tool.poetry]
name = "materials-toolkit"
version = "0.1.0"
description = "materials-toolkit is a python package created to facilitate the development of machine learning models in materials science"
authors = ["Astrid Klipfel <astridklipfel@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "*"
torch_geometric = "^2.3.1"
torch = "^2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
