name: Full unit testing

on:
  push:
    branches:
      - main

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9","3.10","3.11"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
      - name: poetry install
        run: |
          poetry install --with test
          poetry run pip install --upgrade --force-reinstall torch --index-url https://download.pytorch.org/whl/cpu
          poetry run pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.0.0+cpu.html
      - name: poetry test
        run: poetry run pytest